### ISSUE TITLE
Switching between current and previous windows

### ISSUE THREAD

**Issue by asyncee** [oniatsu/HotSwitch-HS#1]
Hi, i saw your last commits and tested them out. I can confirm that switching between current and previous window now works! Thanks :)

Although i had to remove `^` and `@` keys from `ALL_KEYS` to make it.

**Comment by oniatsu** [comment]
Thanks!

I fixed it. https://github.com/oniatsu/HotSwitch-HS/commit/4cf2ce0786913cbaae7e5ba387447b40798ec1e4
The bug occured on the US keyboard layout.
