### ISSUE TITLE
Multiple Libreoffice windows still cause problems with registering keys

### ISSUE THREAD

**Issue by uhkeller** [oniatsu/HotSwitch-HS#2]
Unfortunately I prematurely concluded that everything works now with multiple-window applications over in the Hotswitch issues.

Here's Hotswitch-HS showing, among others, two LibreOffice Windows.

![image](https://user-images.githubusercontent.com/2323704/140483161-9f38e8b4-3103-401c-b8c9-ee8182e34c33.png)

I highlighted the first LibreOffice Window (Untitled 1), hit space and 1, and 1 was registered for the *other* window.

![image](https://user-images.githubusercontent.com/2323704/140483227-6f755a2d-7108-4cdd-9be1-af6f04f7ac95.png)

But it gets weirder. If I try the same again (highlight Untitled 1, hit space and then 1), *both* windows now have the 1 key registered.

![image](https://user-images.githubusercontent.com/2323704/140483528-1a4dfc9d-ed1c-4a5e-886b-a6504157eb86.png)

At first I thought this may be a feature, but key 1 only brings one of them to the front, not both.

If I now try to register a different key (2 in this case) for one of the two windows. *both* are switched to the new key.

![image](https://user-images.githubusercontent.com/2323704/140483746-2997eb7a-eeb2-4520-82fa-2cc28aa584f8.png)

I can switch both windows back to auto-assigned keys by registering key 2 for a window of a different application.

![image](https://user-images.githubusercontent.com/2323704/140483875-c21e57a2-50fd-4e53-bb3e-ec3ed5d9c7ef.png)

At this point, when I first tried it out, I could not assign keys to any of the two LibreOffice windows any more. The space+key input was just ignored. I had to assign the auto-assigned keys to a different window first, then it worked again. But I could not reproduce this for screenshots.

I have not tried this with other applications apart from LibreOffice yet.

Apart from all this: thanks for taking the time to port HotSwitch to Hammerspoon (and thus making me discover Hammerspoon in the first place!).

**Comment by oniatsu** [comment]
Thanks!

Anyway, I fixed the registration when the specified key is already registered on the same app window. https://github.com/oniatsu/HotSwitch-HS/commit/25ec0e189e5d76aa7a4a8e8c73d038a420e6e9ba
The registration way is difficult to understand easily.

**Comment by oniatsu** [comment]
For example, a difficult case is these. Eash windows are on same app.
- win A (index 1 (created first) ) key: undefined 
- win B (index 2 (created second) ) key: undefined
- win C (index 3 (created third) ) If you register a key to this, HotSwitch-HS save the key to index 1. Because HotSwitch-HS saves the array of keys for simple order.
