### ISSUE TITLE
enableAllSpaceWindows doesn't work on multiple screens

### ISSUE THREAD

**Issue by qeisar** [oniatsu/HotSwitch-HS#4]
Thanks for the nice tool

With multiple screens, is it possible to have the switch window shown either on all screens or on the main screen (rather than the active one)?

Right now, it shows only on the active screen and require me to hunt for it. The enableAllSpaceWindows doesn't seem to have an effect with me.

**Comment by oniatsu** [comment]
You want to always show the HotSwitch-HS panel on main screen, aren't you?
If you mean it, there is not the option yet.

**Comment by qeisar** [comment]
Then all screens?

**Comment by oniatsu** [comment]
It is somewhat difficult to show on all screens.
But I'll consider implementing that it always shows on main screen.

**Comment by qeisar** [comment]
Thanks, you can close this if you like. 
Cheers

**Comment by oniatsu** [comment]
I have added the option to show the panel not on main screen but on primary screen.
You can use it on [v2.2.5](https://github.com/oniatsu/HotSwitch-HS/releases/tag/v2.2.5)

Usage: https://github.com/oniatsu/HotSwitch-HS#always-showing-the-panel-on-primary-screen
