### ISSUE TITLE
Ability to (fuzzy) Search Window Titles

### ISSUE THREAD

**Issue by akefirad** [oniatsu/HotSwitch-HS#9]
Is it possible to provide a search functionality so that the user can (fuzzy) search the window by its title? When the list grows it's not easy to find the right window considering the size of icons and fonts. Thanks.

**Comment by oniatsu** [comment]
Like the previous issue, this one is not built on that philosophy.
Its experience is slower, because the fastest experience is obtained by registering the key yourself in advance.
